# 所有的关于数据库方面的配置放到这里

spring:
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.43.102:3306/leetcode?useSSL=false&userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 612001
    type: com.zaxxer.hikari.HikariDataSource # 使用数据源默认光 Hikari
  # redis
  redis:
    host: 192.168.43.102
    port: 6379
  config:
    activate:
      on-profile: db
#mp
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台输出的日志.
    # 开启驼峰映射
    map-underscore-to-camel-case: true
  # 逻辑删除
  global-config:
    db-config:
      logic-delete-field: false  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 1代表已经删除
      logic-not-delete-value: 0 # 0代表没有删除
